# Generated by Django 6.0.3 on 2026-03-27 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('TRANCADA', 'Trancada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=10)),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('data_trancamento', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='students.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Aproveitamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_origem', models.CharField(max_length=200)),
                ('instituicao_origem', models.CharField(max_length=200)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aproveitamentos', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Aproveitamento',
                'verbose_name_plural': 'Aproveitamentos',
            },
        ),
        migrations.CreateModel(
            name='RevisaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_atual', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_revisada', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida')], default='PENDENTE', max_length=11)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='assessments.avaliacao')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes_nota', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Revisão de Nota',
                'verbose_name_plural': 'Revisões de Nota',
            },
        ),
        migrations.CreateModel(
            name='SegundaChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=10)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundas_chamadas', to='assessments.avaliacao')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundas_chamadas', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Segunda Chamada',
                'verbose_name_plural': 'Segundas Chamadas',
            },
        ),
    ]
