# Generated by Django 6.0.3 on 2026-04-10 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('TRANCADA', 'Trancada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=10)),
                ('media_final', models.FloatField(blank=True, null=True)),
                ('progresso', models.FloatField(default=0.0, help_text='Percentual de conclusão (0–100)')),
                ('carga_horaria_cumprida', models.PositiveIntegerField(default=0, help_text='Em horas')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(max_length=20, unique=True)),
                ('data_ingresso', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=11)),
                ('justificativa', models.TextField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='students.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='courses.curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='regra_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='courses.regracurso'),
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_origem', models.CharField(max_length=200)),
                ('disciplina_origem', models.CharField(max_length=200)),
                ('disciplina_destino', models.CharField(max_length=200)),
                ('aprovado', models.BooleanField(default=False)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Equivalência',
                'verbose_name_plural': 'Equivalências',
            },
        ),
        migrations.CreateModel(
            name='Aproveitamento',
            fields=[
                ('solicitacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.solicitacao')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aproveitamentos', to='courses.modulo')),
            ],
            options={
                'verbose_name': 'Aproveitamento',
                'verbose_name_plural': 'Aproveitamentos',
            },
            bases=('students.solicitacao',),
        ),
        migrations.CreateModel(
            name='RevisaoNota',
            fields=[
                ('solicitacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.solicitacao')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='assessments.avaliacao')),
            ],
            options={
                'verbose_name': 'Revisão de Nota',
                'verbose_name_plural': 'Revisões de Nota',
            },
            bases=('students.solicitacao',),
        ),
        migrations.CreateModel(
            name='SegundaChamada',
            fields=[
                ('solicitacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.solicitacao')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundas_chamadas', to='assessments.avaliacao')),
            ],
            options={
                'verbose_name': 'Segunda Chamada',
                'verbose_name_plural': 'Segundas Chamadas',
            },
            bases=('students.solicitacao',),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'curso')},
        ),
    ]
