# Generated by Django 6.0.3 on 2026-04-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva'), ('DISCURSIVA', 'Discursiva'), ('PROJETO_PRATICO', 'Projeto Prático'), ('PROVA_MONITORADA', 'Prova com Monitoramento Remoto')], max_length=20)),
                ('peso', models.FloatField(default=1.0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='courses.modulo')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Avaliação Realizada',
                'verbose_name_plural': 'Avaliações Realizadas',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDiscursiva',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.avaliacao')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Avaliação Discursiva',
                'verbose_name_plural': 'Avaliações Discursivas',
            },
            bases=('assessments.avaliacao',),
        ),
        migrations.CreateModel(
            name='AvaliacaoObjetiva',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.avaliacao')),
                ('questoes', models.JSONField(default=list, help_text='Lista de questões objetivas')),
            ],
            options={
                'verbose_name': 'Avaliação Objetiva',
                'verbose_name_plural': 'Avaliações Objetivas',
            },
            bases=('assessments.avaliacao',),
        ),
        migrations.CreateModel(
            name='ProjetoPratico',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.avaliacao')),
                ('repositorio', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Projeto Prático',
                'verbose_name_plural': 'Projetos Práticos',
            },
            bases=('assessments.avaliacao',),
        ),
        migrations.CreateModel(
            name='ProvaMonitorada',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.avaliacao')),
                ('monitoramento_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prova Monitorada',
                'verbose_name_plural': 'Provas Monitoradas',
            },
            bases=('assessments.avaliacao',),
        ),
    ]
