# Generated by Django 6.0.3 on 2026-03-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva'), ('DISCURSIVA', 'Discursiva'), ('PROJETO_PRATICO', 'Projeto Prático'), ('PROVA_MONITORADA', 'Prova com Monitoramento Remoto')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='courses.modulo')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='TrabalhoPratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos_praticos', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Trabalho Prático',
                'verbose_name_plural': 'Trabalhos Práticos',
            },
        ),
    ]
