# Generated by Django 6.0.3 on 2026-04-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaorealizada',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas', to='students.aluno'),
        ),
        migrations.AddField(
            model_name='avaliacaorealizada',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='assessments.avaliacao'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaorealizada',
            unique_together={('aluno', 'avaliacao')},
        ),
    ]
