# Generated by Django 6.0.3 on 2026-03-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.PositiveIntegerField(help_text='Em horas')),
                ('nota_minima', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['curso', 'ordem'],
                'unique_together': {('curso', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='courses.curso')),
                ('curso_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigido_por', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Pré-requisito',
                'verbose_name_plural': 'Pré-requisitos',
                'unique_together': {('curso', 'curso_requerido')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, related_name='requerido_por', through='courses.PreRequisito', to='courses.curso'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(blank=True)),
                ('duracao', models.PositiveIntegerField(help_text='Em minutos')),
                ('ordem', models.PositiveIntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='courses.modulo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'ordem')},
            },
        ),
    ]
