# Generated by Django 6.0.3 on 2026-04-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Em horas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_minima', models.FloatField(default=6.0)),
                ('carga_horaria_minima', models.PositiveIntegerField(default=0, help_text='Em horas')),
                ('exige_projeto_final', models.BooleanField(default=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regra de Curso',
                'verbose_name_plural': 'Regras de Curso',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['curso', 'ordem'],
                'unique_together': {('curso', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('MODULO', 'Módulo')], max_length=10)),
                ('referencia_id', models.PositiveIntegerField(help_text='ID do Curso ou Módulo exigido')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisitos', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Pré-requisito',
                'verbose_name_plural': 'Pré-requisitos',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(blank=True)),
                ('duracao', models.PositiveIntegerField(help_text='Em minutos')),
                ('ordem', models.PositiveIntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='courses.modulo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'ordem')},
            },
        ),
    ]
