# Generated by Django 5.2.15 on 2026-06-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regracurso',
            options={'ordering': ['curso', '-data_inicio'], 'verbose_name': 'Regra de Curso', 'verbose_name_plural': 'Regras de Curso'},
        ),
        migrations.AddField(
            model_name='regracurso',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='courses.curso'),
        ),
    ]
