# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


def remove_orphan_course_rules(apps, schema_editor):
    RegraCurso = apps.get_model("courses", "RegraCurso")
    RegraCurso.objects.filter(curso__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_regracurso_options_regracurso_curso"),
    ]

    operations = [
        migrations.RunPython(remove_orphan_course_rules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="regracurso",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regras",
                to="courses.curso",
            ),
        ),
    ]
