from typing import Protocol


class CertificateRepository(Protocol):
    def get_or_create(self, enrollment, *, expiration=None): ...
    def has_completed_project(self, enrollment, *, minimum_grade: float) -> bool: ...
    def has_severe_integrity_incident(self, enrollment) -> bool: ...
    def save(self, certificate, *, fields: list[str]) -> None: ...
