# Generated by Django 6.0.3 on 2026-04-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, help_text='Deixar em branco para certificado vitalício', null=True)),
                ('status', models.CharField(choices=[('EMITIDO', 'Emitido'), ('SUSPENSO', 'Suspenso'), ('REVOGADO', 'Revogado')], default='EMITIDO', max_length=10)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='IncidenteIntegridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COLA', 'Cola'), ('PLAGIO', 'Plágio'), ('FRAUDE', 'Fraude'), ('OUTROS', 'Outros')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Incidente de Integridade',
                'verbose_name_plural': 'Incidentes de Integridade',
            },
        ),
    ]
