# Generated by Django 6.0.3 on 2026-03-27 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteIntegridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave')], max_length=5)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_AVALIACAO', 'Em Avaliação pelo Comitê'), ('SUSPENSAO', 'Suspensão'), ('REVOGACAO', 'Revogação'), ('ENCERRADO', 'Encerrado sem penalidade')], default='PENDENTE', max_length=12)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='students.matricula')),
            ],
            options={
                'verbose_name': 'Incidente de Integridade',
                'verbose_name_plural': 'Incidentes de Integridade',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, help_text='Deixar em branco para certificado vitalício', null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='students.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='courses.curso')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
