# Generated by Django 5.2.15 on 2026-06-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenteintegridade',
            name='gravidade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('GRAVE', 'Grave')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='validade',
            field=models.DateField(blank=True, help_text='Deixar em branco para certificado vitalicio', null=True),
        ),
        migrations.AlterField(
            model_name='incidenteintegridade',
            name='tipo',
            field=models.CharField(choices=[('COLA', 'Cola'), ('PLAGIO', 'Plagio'), ('FRAUDE', 'Fraude'), ('OUTROS', 'Outros')], max_length=10),
        ),
    ]
