from typing import Protocol


class StudentRepository(Protocol):
    def get_or_create_student(self, user): ...

    def find_enrollment(self, student, course): ...

    def enroll(self, student, course): ...

    def save_enrollment(self, enrollment, *, fields: list[str]) -> None: ...
